### ISSUE TITLE
How to debug PATH_TOLERANCE_VIOLATED error

### ISSUE THREAD

**Issue by jacknlliu** [ros-controls/ros_controllers#300]
I'm debugging a issue about 
```
[ WARN] [1508834853.402216761, 3680.601000000]: Controller arm_controller failed with error code PATH_TOLERANCE_VIOLATED
[ WARN] [1508834853.402397314, 3680.602000000]: Controller handle arm_controller reports status ABORTED
[ INFO] [1508834853.701254652, 3680.896000000]: ABORTED: Solution found but controller failed during execution
```

Could someone give more details about how reflect the path tolerance config from the `controller/state`? Is the `error` in `controller/state` equal to `path tolerance`?

The configuration of controller is
```
arm_gazebo_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}

  gains:
      shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
```
