### ISSUE TITLE
suggest adding progress feedback in joint_trajectory_controller

### ISSUE THREAD

**Issue by itfanr** [ros-controls/ros_controllers#387]
joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h

Joint_trajectory_controller works with trajectory generated by moveit, and gets lots of points by sampling.

But I want to know the progress feedback indicate where robot now and show users on HMI or graph user interface.

So, I think we should add progress feedback  obviously in percent.

And now, I make feedback by minus the time by myself with output from follow_joint_trajectory/feedback :
```
header: 
  seq: 719
  stamp: 
    secs: 1746
    nsecs: 556000000
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1729
      nsecs: 454000000
    id: "/move_group-5-1729.454000000"
  status: 3
  text: ''
feedback: 
  header: 
    seq: 0
    stamp: 
      secs: 1746
      nsecs: 469000000
    frame_id: ''
```

related issue:
https://github.com/ros-controls/ros_controllers/issues/173
