### ISSUE TITLE
Add lazy publisher for controller state

### ISSUE THREAD

**Issue by bit-pirate** [ros-controls/ros_controllers#41]
And maybe an additional parameter for the state publisher frequency.

**Comment by adolfo-rt** [comment]
+1 for the lazy publisher.

The parameter is already there. It needs to get documented. It's called `state_publish_rate`. This is an example controller configuration file:

``` yaml
head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

  constraints:
    goal_time: 0.6                   # Defaults to zero
    stopped_velocity_tolerance: 0.02 # Defaults to 0.01
    head_1_joint:
      trajectory: 0.05 # Not enforced if unspecified
      goal: 0.02       # Not enforced if unspecified
    head_2_joint:
      goal: 0.01

  state_publish_rate:  25 # Defaults to 50
  action_monitor_rate: 10 # Defaults to 20
  hold_trajectory_duration: 0 # Defaults to 0.5
```
