### ISSUE TITLE
TrajectoryReplacement does not merge Trajectories

### ISSUE THREAD

**Issue by beschaef** [ros-controls/ros_controllers#421]
Hey Guys,
i'm trying to use the joint_trajectory_controller. Moving the Robot with Trajectories works really fine. But when i send a new Traj before the old one finished the robot is going to stop and then start the new trajectory. So the replacement is working, but the Trajecotories are not "merged".
Have you any idea what is going wrong?

Thanks for your help :)

Snippet of my launchfine
```xml
<arg name="spawn_controllers"
         default="$(eval 'arm_controller' + ' joint_state_controller')" />

    <rosparam command="load" file="$(find horst_driver)/config/controller_config.yaml" />

    <node name="controller_spawner" pkg="controller_manager" type="spawner"
          args="$(arg spawn_controllers)" />
```
controller_config.yaml
```yaml
joint_names: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  #type: position_controllers/JointTrajectoryController
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint_1 #  same for 2-6
  publish_rate: 50

  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 10,  d: 1, i: 1, i_clamp: 1} #  same for 2-6


  velocity_ff:
    joint_1: 1.0  #  same for 2-6

  constraints:
    stopped_velocity_tolerance: 0.02 # Override default
    joint_1: # same for 2-6
      trajectory: 0.005
  stop_trajectory_duration: 0
```
