### ISSUE TITLE
Upcoming Melodic release

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros_controllers#467]
Wishlist:

* #469 

 @ipa-mdl  @matthew-reynolds & whoever else is reading this, please feel free to add your preferred issues/PR-s to be addressed here and we will try to prioritize.

**Comment by callen5914** [comment]
Yes please document implement much better. It's lousy!

**Comment by bmagyar** [comment]
@callen5914 if there's a specific thing you have problems with we can try taking a look.

**Comment by callen5914** [comment]
@bmagyar I have some issues with implementing the Ackermann Steering Controller.

To be a little more specific: 

1. The [Wiki](http://wiki.ros.org/ackermann_steering_controller) states you need a YAML file with a minimal setup as follows.

```yaml
mobile_base_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  rear_wheel: 'rear_wheel_joint'
  front_steer: 'front_steer_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

```

So does it matter where this yaml file located. Do I need to copy and paste the header files and the cpp file to my package some where? On the wiki they say you can get the gazebo sim plugin from this really old cirkit-03. None of this makes any sense.

Cheers,
