### ISSUE TITLE
[joint_state_controller] Allow to publish joints not present in RobotHW

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_controllers#87]
Inspired by ros-simulation/gazebo_ros_pkgs#141.

Robots sometimes have joints that can't be controlled, or don't even have sensing devices like encoders. A typical example would be a non-driven caster wheel.

In simulated scenarios the state of such joints can be reconstructed as one can add sensors for free, but this can be a problem with real hardware. If no state is available for these joints, ROS tools like tf and the Rviz plugins that depend on it will fail to reconstruct parts of the robot.

One possibility to address this issue would be to extend the `joint_state_controller` to publish additional joints with a predefined constant value. A controller configuration file could look like so:

``` yaml
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  # This is the new part that this ticket would address. It's optional
  extra_joints:
    foo_joint: 0.0 # Name: position
    bar_joint: 0.5
```

Implementation-wise, one would have to take care that there is no overlap between the robot joints and the extra ones.
